import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { UserProvider } from '@/contexts/userContext'
import { RoleProvider } from '@/contexts/roleContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
      <UserProvider>
        <RoleProvider>
          <Header></Header>
          {children}
        </RoleProvider>
      </UserProvider>
      </body>
    </html>
  )
}
