import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import { UserProvider } from '@/contexts/userContext';
import { AlertProvider } from '@/contexts/alertContext';
import { Role } from '@/components/hooks/Role';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AlertProvider>
          <UserProvider>
            <div className="flex h-screen flex-col">
              <Header></Header>
              {children}
            </div>
          </UserProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
